 ($
 (// Пример процедуры)
 (// Определение процедуры) 
 (defun my_func (params x y a)
   ($ (set! s (arif 1 * x * x + 2 * y * y + 3 * a * a))
   (print s)
   (return) ))
 (defun my_func2 (pass)
    ($ (print a)
    (return)   ))
 (// вызов процедуры)  
 (defun main (pass)(
    ($(call my_func(args 2 3 4))(call my_func2(pass))
     )              )
  )
  )